# Generated by Django 6.0 on 2025-12-18 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AirportRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")], max_length=5
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration (KM or Minutes)"),
                ),
                (
                    "child_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_routes",
                        to="routes.airport",
                    ),
                ),
                (
                    "parent_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_routes",
                        to="routes.airport",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent_airport", "position")},
            },
        ),
    ]
